### ISSUE TITLE
V6 schematics causes rapid ghost left/right events on C64 joystickport1

### ISSUE THREAD

**Issue by rainisto** [screwbreaker/OpenC64MegaDrivePadAdapter#1]
If I revert back to V5 by putting jumper wire on R5 ghost events disappear on C64 joystickport1. Port2 works normally,

**Comment by screwbreaker** [comment]
I'm working on a new revision.
To fix the issue I'm working on a version where R5 still in place. But pot_y is disconnected in the C64 mode.

**Comment by screwbreaker** [comment]
I released the v7
The issue should be fixed.
I tested it on both Amiga and C64, and I have no issue.
